require("config.colors")
require("config.monitors")
require("config.input")
require("config.looks")
require("config.workspaces")
require("config.windowrules")
require("config.keybinds")
require("config.autostart")
