$image = /home/pimp/rehypr/hyprland/.config/hypr/wallpapers/inkbound.png

$background = rgba(181215ff)

$error = rgba(ffb4abff)

$error_container = rgba(93000aff)

$inverse_on_surface = rgba(362e33ff)

$inverse_primary = rgba(834c74ff)

$inverse_surface = rgba(ecdfe5ff)

$on_background = rgba(ecdfe5ff)

$on_error = rgba(690005ff)

$on_error_container = rgba(ffdad6ff)

$on_primary = rgba(4f1e43ff)

$on_primary_container = rgba(ffd7efff)

$on_primary_fixed = rgba(36072dff)

$on_primary_fixed_variant = rgba(69355bff)

$on_secondary = rgba(3e2a38ff)

$on_secondary_container = rgba(fadaecff)

$on_secondary_fixed = rgba(281622ff)

$on_secondary_fixed_variant = rgba(56404fff)

$on_surface = rgba(ecdfe5ff)

$on_surface_variant = rgba(d2c2caff)

$on_tertiary = rgba(4b2717ff)

$on_tertiary_container = rgba(ffdbcdff)

$on_tertiary_fixed = rgba(321205ff)

$on_tertiary_fixed_variant = rgba(663c2bff)

$outline = rgba(9b8d94ff)

$outline_variant = rgba(4f444aff)

$primary = rgba(f6b2e0ff)

$primary_container = rgba(69355bff)

$primary_fixed = rgba(ffd7efff)

$primary_fixed_dim = rgba(f6b2e0ff)

$scrim = rgba(000000ff)

$secondary = rgba(dcbed0ff)

$secondary_container = rgba(56404fff)

$secondary_fixed = rgba(fadaecff)

$secondary_fixed_dim = rgba(dcbed0ff)

$shadow = rgba(000000ff)

$source_color = rgba(3e2837ff)

$surface = rgba(181215ff)

$surface_bright = rgba(3f373bff)

$surface_container = rgba(251e22ff)

$surface_container_high = rgba(2f282cff)

$surface_container_highest = rgba(3a3337ff)

$surface_container_low = rgba(201a1eff)

$surface_container_lowest = rgba(120c10ff)

$surface_dim = rgba(181215ff)

$surface_tint = rgba(f6b2e0ff)

$surface_variant = rgba(4f444aff)

$tertiary = rgba(f5b9a1ff)

$tertiary_container = rgba(663c2bff)

$tertiary_fixed = rgba(ffdbcdff)

$tertiary_fixed_dim = rgba(f5b9a1ff)

