source = ~/rehypr/hyprland/.config/hypr/colors.conf

# BACKGROUND
background {
    monitor =
    #path = screenshot
    path = /home/pimp/rehypr/hyprland/.config/hypr/wallpapers/inkbound.png
    color = $background
    blur_passes = 4
    contrast = 1
    brightness = 0.5
    vibrancy = 0.2
    vibrancy_darkness = 0.2
}

# GENERAL
general {
    hide_cursor = true
    grace = 10
    disable_loading_bar = true
    ignore_empty_input = true
}

animations {
    animation = fadeIn, 0, 0, linear
    animation = fadeOut, 0, 0, linear
}

# INPUT FIELD
input-field {
    hide_input = true
    monitor =
    size = 300, 100
    outline_thickness = 0
    dots_size = 0.2
    dots_spacing = 0.2
    dots_center = true
    outer_color = rgba(200, 200, 200, 0)
    inner_color = rgba(200, 200, 200, 0)
    font_color = $primary
    swap_font_color = true
    fade_on_empty = true
    rounding = -1
    check_color = #2EB095
    capslock_color = #960000
    halign = center
    valign = center
    position = 0, -120
    placeholder_text =
    fail_text = wrong pwd
}

# DATE
label {
    monitor =
    text = cmd[update:60000] date "+%A, %B %d"
    color = $primary
    font_size = 32
    font_family = Noto Sans
    position = 0, 120
    halign = center
    valign = center
}

# TIME
label {
    monitor =
    text = $TIME12
    color = $primary
    font_size = 128
    font_family = Noto Sans Bold
    position = 0, 0
    halign = center
    valign = center
}
