general {
    lock_cmd = sh -c 'hyprctl switchxkblayout all 0; pidof hyprlock >/dev/null || exec hyprlock'

    before_sleep_cmd = sh -c 'hyprctl switchxkblayout all 0; pidof hyprlock >/dev/null || exec hyprlock --no-fade-in'

    after_sleep_cmd = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'

    inhibit_sleep = 3
}

listener {
    timeout = 60
    on-timeout = hyprctl dispatch 'hl.dsp.dpms({ action = "disable" })'
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}

listener {
    timeout = 300
    on-timeout = systemctl sleep
    on-resume = hyprctl dispatch 'hl.dsp.dpms({ action = "enable" })'
}
