shell /usr/sbin/fish
include colors.conf
font_family      RobotoMonoNerd
font_size        16
cursor_trail 1
window_padding_width 10

enabled_layouts splits,tall,stack,fat,grid,horizontal,vertical
map ctrl+shift+return combine : goto_layout splits : launch --location=vsplit --cwd=current

draw_minimal_borders yes

tab_bar_style powerline
tab_powerline_style round
active_tab_background #abd290
inactive_tab_background #1d211a
tab_title_template " {index}  {title} "
